# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(315, 264)
        MainWindow.setStyleSheet("background:purple;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.generator = QtWidgets.QLabel(self.centralwidget)
        self.generator.setGeometry(QtCore.QRect(40, 10, 111, 16))
        self.generator.setStyleSheet("background:black;\n"
"color:white;\n"
"border: 1px solid red;\n"
"border-radius:10px;")
        self.generator.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.generator.setObjectName("generator")
        self.code_create = QtWidgets.QPushButton(self.centralwidget)
        self.code_create.setGeometry(QtCore.QRect(110, 40, 93, 28))
        self.code_create.setStyleSheet("color:white;\n"
"background:black;\n"
"border:2px solid purple;\n"
"border-radius:10px ;\n"
"\n"
"")
        self.code_create.setObjectName("code_create")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(160, 10, 123, 16))
        self.password_label.setStyleSheet("background:black;\n"
"color:white;\n"
"border: 1px solid red;\n"
"border-radius: 9px;")
        self.password_label.setObjectName("password_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "logika"))
        self.generator.setText(_translate("MainWindow", "Генератор паролів"))
        self.code_create.setText(_translate("MainWindow", "згенерувати"))
        self.password_label.setText(_translate("MainWindow", "тут буде ваш пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
